//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZapatukiFinal.Repositories.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.PRODUCT_CART = new HashSet<PRODUCT_CART>();
        }
    
        public int IdProduct { get; set; }
        public int IdProductType { get; set; }
        public int IdSupplier { get; set; }
        public string Name { get; set; }
        public string Brand { get; set; }
        public string Reference { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
        public string Description { get; set; }
        public int Stock { get; set; }
        public double Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT_CART> PRODUCT_CART { get; set; }
        public virtual PRODUCT_TYPE PRODUCT_TYPE { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
    }
}
